# Generated by Django 3.0.4 on 2020-05-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcateg', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='Tag')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('sourceimg', models.CharField(max_length=100, verbose_name='Imagen de Categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categoria',
                'ordering': ['createdat'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci_ruc', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Cédula de Identidad/RUC')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Página Web')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
                ('provincia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia')),
                ('canton', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cantón')),
                ('cp', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código Postal')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('notas', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notas')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
                'ordering': ['-createdat'],
            },
        ),
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('idinteresado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'interesado',
                'verbose_name_plural': 'interesados',
                'db_table': 'interesado',
                'ordering': ['createdat'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iditem', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('preciounit', models.FloatField(verbose_name='Precio Unitario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'ítem',
                'verbose_name_plural': 'ítems',
                'db_table': 'item',
                'ordering': ['createdat'],
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Correo electrónico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'suscriptor',
                'verbose_name_plural': 'suscriptores',
                'db_table': 'suscriptor',
                'ordering': ['-createdat'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idproy', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('sourceimg', models.CharField(blank=True, max_length=200, null=True, verbose_name='Imagen del Proyecto')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('ci_ruc', models.ForeignKey(blank=True, db_column='ci_ruc', null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministracionBTM.Cliente', verbose_name='Cliente')),
                ('idcateg', models.ForeignKey(blank=True, db_column='idcateg', null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministracionBTM.Categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'db_table': 'proyecto',
                'ordering': ['createdat'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idimagen', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('pathimg', models.CharField(max_length=100, verbose_name='Path')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('idproy', models.ForeignKey(blank=True, db_column='idproy', null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministracionBTM.Proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imágenes',
                'db_table': 'imagen',
                'ordering': ['createdat'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('idcot', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo')),
                ('condicionpago', models.CharField(max_length=100, verbose_name='Condición de Pago')),
                ('tiempoestimado', models.CharField(max_length=100, verbose_name='Tiempo Estimado')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('ci_ruc', models.ForeignKey(blank=True, db_column='ci_ruc', null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministracionBTM.Cliente', verbose_name='Cliente')),
                ('iditem', models.ManyToManyField(to='AdministracionBTM.Item')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'db_table': 'cotizacion',
                'ordering': ['createdat'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idcomentario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('nombres', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('idproy', models.ForeignKey(blank=True, db_column='idproy', null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministracionBTM.Proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'db_table': 'comentario',
                'ordering': ['createdat'],
            },
        ),
    ]
