# Generated by Django 2.2 on 2020-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionBTM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='0999999999', max_length=20, verbose_name='Teléfono'),
        ),
    ]
